# Final Part Two
Jiajing Zheng

In [1]:
import quandl
import pandas as pd
n = range(1,21)
nms = ["CHRIS/CME_ED"+str(i) for i in n]
dfs = [quandl.get(nm, authtoken=token) for nm in nms]

In [2]:
dfs

[              Open    High     Low    Last  Change  Settle    Volume  \
 Date                                                                   
 1982-02-01  84.020  84.110  83.740  83.740     NaN  83.740     423.0   
 1982-02-02  83.770  84.100  83.770  83.880     NaN  83.880     777.0   
 1982-02-03  83.960  84.100  83.710  83.730     NaN  83.730     619.0   
 1982-02-04  83.880  84.010  83.750  83.850     NaN  83.850     454.0   
 1982-02-05  83.900  83.990  83.750  83.850     NaN  83.850     311.0   
 ...            ...     ...     ...     ...     ...     ...       ...   
 2021-06-23  99.865  99.870  99.855  99.855  -0.010  99.860  119833.0   
 2021-06-24  99.855  99.860  99.855  99.860  -0.005  99.855   97875.0   
 2021-06-25  99.855  99.860  99.850  99.860     NaN  99.855   75350.0   
 2021-06-28  99.855  99.860  99.850  99.850     NaN  99.855   98784.0   
 2021-06-29  99.855  99.855  99.850  99.855     NaN  99.855   54513.0   
 
             Previous Day Open Interest  
 Date  

In [3]:
df = pd.DataFrame()
for i in range(len(dfs)):
    df['ED' + str(i+1)] = dfs[i]['Settle']['2000':]

In [4]:
df

ED1     ED2     ED3     ED4     ED5     ED6     ED7     ED8  \
Date                                                                         
2000-01-03  93.780  93.445  93.220  92.990  92.975  92.885  92.840  92.770   
2000-01-04  93.795  93.495  93.265  93.045  93.030  92.940  92.895  92.820   
2000-01-05  93.790  93.450  93.210  92.995  92.975  92.880  92.830  92.750   
2000-01-06  93.790  93.470  93.240  93.035  93.015  92.920  92.865  92.785   
2000-01-07  93.795  93.510  93.280  93.090  93.070  92.975  92.930  92.845   
...            ...     ...     ...     ...     ...     ...     ...     ...   
2021-06-23  99.860  99.790  99.795  99.720  99.625  99.470  99.360  99.225   
2021-06-24  99.855  99.785  99.785  99.710  99.615  99.460  99.350  99.215   
2021-06-25  99.855  99.785  99.790  99.710  99.610  99.450  99.335  99.195   
2021-06-28  99.855  99.790  99.795  99.720  99.625  99.470  99.355  99.215   
2021-06-29  99.855  99.790  99.795  99.720  99.625  99.470  99.355  99.210   

               ED9    ED10    ED11    ED12    ED13    ED14    ED15    ED16  \
Date                                                                         
2000-01-03  92.815  92.805  92.795  92.735  92.765  92.740  92.720  92.640   
2000-01-04  92.865  92.855  92.845  92.790  92.820  92.795  92.775  92.695   
2000-01-05  92.785  92.775  92.760  92.700  92.730  92.705  92.680  92.595   
2000-01-06  92.825  92.815  92.800  92.740  92.770  92.745  92.725  92.640   
2000-01-07  92.885  92.875  92.860  92.800  92.830  92.805  92.785  92.700   
...            ...     ...     ...     ...     ...     ...     ...     ...   
2021-06-23  99.005  98.875  98.765  98.655  98.545  98.450  98.390  98.320   
2021-06-24  98.995  98.860  98.750  98.640  98.535  98.440  98.380  98.315   
2021-06-25  98.970  98.835  98.720  98.605  98.495  98.400  98.340  98.275   
2021-06-28  98.995  98.865  98.745  98.630  98.520  98.425  98.370  98.305   
2021-06-29  98.990  98.860  98.740  98.625  98.520  98.425  98.370  98.310   

              ED17    ED18    ED19    ED20  
Date                                        
2000-01-03  92.645  92.600  92.570  92.480  
2000-01-04  92.700  92.655  92.625  92.535  
2000-01-05  92.600  92.555  92.520  92.425  
2000-01-06  92.645  92.600  92.565  92.470  
2000-01-07  92.705  92.660  92.625  92.530  
...            ...     ...     ...     ...  
2021-06-23  98.260  98.190  98.145  98.085  
2021-06-24  98.260  98.190  98.145  98.090  
2021-06-25  98.215  98.145  98.100  98.045  
2021-06-28  98.255  98.190  98.155  98.105  
2021-06-29  98.260  98.195  98.160  98.110  

[5391 rows x 20 columns]

In [12]:
df_train = df[(df.index >= "2012-01-01") & (df.index < "2015-01-01")]
df_cv = df[(df.index >= "2015-01-01") & (df.index < "2017-01-01")]
df_test = df[(df.index >= "2017-01-01") & (df.index < "2018-01-01")]

In [6]:
train_beg = df[df.index < "2012-01-01"].shape[0]
train_end = df[df.index < "2015-01-01"].shape[0]
cv_beg = train_end
cv_end = df[df.index < "2017-01-01"].shape[0]
test_beg = cv_end
test_end = df[df.index < "2018-01-01"].shape[0]
train_beg, train_end, cv_beg, cv_end, test_beg, test_end

(3010, 3755, 3755, 4259, 4259, 4510)

# 1. Use Sample A to compute 4 cointegrated pairs of futures rates: [3y,4y], [4y,5y], [2y,4y],[3y,5y]

In [7]:
import statsmodels.api as sm

def CCA_Chou_Ng(data_set):
    
    #data_set is pandas dataframe
    
    #define df_lag as the 1-period lag of data_set
    df_lag = data_set.shift(1).dropna()
    
    #drop the 0-index of data_set to make sure df and df_lag are aligned
    df = data_set.drop(data_set.index[0]).dropna()
    n = len(data_set.columns)
    
    #X(t) ~ M_1 + X(t-1)
    
    # input variables
    X = df_lag.values
    
    # ensures there is an intercept
    X_I = sm.add_constant(X)
    
    # regression target
    Y = df.values
    
    # fit regression
    l1 = sm.OLS(Y,X_I).fit()
    
    # get the coefficients/betas without the intercept
    B=l1.params[1:(n+1)]
    #print(B)
    
    #X(t-1) ~ M_2 + X(t)
    
    # regression, reversing the dependent and the independent
    Y_I = sm.add_constant(Y)
    l2 = sm.OLS(X,Y_I).fit()
    
    # get the coefficients/betas without the intercept
    A=l2.params[1:(n+1)]
    #print(A)
    
    # take the dot product of the two coefficient matrices
    C = np.dot(A,B)
    print(C)
    eig_val, eig_vec = np.linalg.eig(C)
    return eig_val, eig_vec, C

In [8]:
import numpy as np
pair = [[3, 4], [4, 5], [2, 4], [3, 5]]
pair_dict = {}
weight_dict = {}
result_dict = {}
for i in range(len(pair)):
    pair_dict[i] = df[[f"ED{j*4}" for j in pair[i]]]
    e_val, e_vec, C = CCA_Chou_Ng(pair_dict[i].iloc[train_beg: train_end,:])
    weight_dict[i] = e_vec[:, np.argsort(e_val)[0]] / e_vec[0, np.argsort(e_val)[0]]
    result_dict[i] = pair_dict[i] @ weight_dict[i].T 

[[ 0.93190263 -0.04494545]
 [ 0.04252444  1.02305741]]
[[0.92442655 0.00320279]
 [0.06189928 0.98386093]]
[[ 0.94590313 -0.0419542 ]
 [ 0.01235482  1.00276887]]
[[ 0.95264879 -0.01002157]
 [ 0.02567164  0.99514239]]


# 2. Use the same Sample A to construct the following: a. AR(1) model fitted to each of the 4 cointegrated pairs (Signal 1) b. AR(1) model fitted to each {cointegrated pair - EMA()} (Signal 2)

In [9]:
from statsmodels.tsa.ar_model import AutoReg
def signal(df, lambd, train_beg, train_end, cv_beg, cv_end):
    df_train = df.iloc[train_beg: train_end]
    df2 = df - df.ewm(alpha=lambd).mean()
    df_train2 = df2.iloc[train_beg: train_end]
    
    AR_1 = AutoReg(df_train.values, lags=1)
    AR_2 = AutoReg(df_train2.values, lags=1)
    
    res1 = AR_1.fit()
    res2 = AR_2.fit()
    
    s_1 = df.iloc[cv_beg: cv_end] - AR_1.predict(params=res1.params, start=cv_beg, end=cv_end-1)
    s_2 = df2.iloc[cv_beg: cv_end] - AR_2.predict(params=res2.params, start=cv_beg, end=cv_end-1)

    return s_1, s_2

In [10]:
df_value = result_dict[1].dropna()
s_1, s_2 = signal(df_value, 0.13, train_beg, train_end, train_beg, train_end)
np.corrcoef(s_1, s_2)

array([[1.        , 0.30506573],
       [0.30506573, 1.        ]])

# 3. Compute half-lives for all signals. Pick  to make sure that half-life of Signal 2 is ~5 da

In [11]:
def halflife(x):
    x_lag = x.shift(1)
    x_lag.iloc[0] = x_lag.iloc[1]
    x_ret = x - x_lag
    x_ret.iloc[0] = x_ret.iloc[1]

    x_lag2 = sm.add_constant(x_lag)
    model = sm.OLS(x_ret,x_lag2)
    res = model.fit()

    halflife = round(-np.log(2) / list(res.params)[1], 4)
    return halflife

In [119]:
pair = [[3, 4], [4, 5], [2, 4], [3, 5]]
for i in range(len(pair)):
    result_dict[i] = result_dict[i].dropna()
    s_1, s_2 = signal(result_dict[i],0.114, train_beg, train_end, train_beg, train_end)
    print('for {}: signal1 halflife is {}, signal2 halflife is {}'.format(pair[i], halflife(s_1), halflife(s_2)))


for [3, 4]: sig_1 halflife is 34.0089, sig_2 halflife is 3.0012
for [4, 5]: sig_1 halflife is 44.3839, sig_2 halflife is 5.4201
for [2, 4]: sig_1 halflife is 34.4735, sig_2 halflife is 3.1948
for [3, 5]: sig_1 halflife is 40.7162, sig_2 halflife is 5.9136


# 4. Signal 3 is a linear combination(mixture) of signals 1 & 2. Weight of the mixture, ; is a hyper-parameter you can try to determine by maximizing a signal quality metric in Cross- Validation Sample B. For simplicity, we will only use all the AR(1) estimations from the Training Sample A.

a. Signal quality metric will measure predictibility of the forecast, E[z(t+H)|t] for Sig- nals 1,2,3 and all cointegrated pairs z(t). Use Spearman rank-based correlation
between the forecast and actual as a signal quality metric

In [152]:
import statsmodels.api as sm
from scipy.stats import spearmanr

def signal3(theta, s_1, s_2):
    s_3 = theta * s_1 + (1 - theta) * s_2
    return s_3


def predict(s,y,h):
    x = sm.add_constant(s).shift(h)[h:]
    AR_1 = sm.OLS(y,x)
    res = AR_1.fit()
    pred = res.predict(x)
    a = pred - z_t
    coef, p =spearmanr(y, pred)
    
    a_position = []
    for i in range(len(a)):
        if abs(a[i])>0.1:
            a_position.append(i)
            
    if (len(a_position)):
        coef_a, p_a  = spearmanr(y.iloc[a_position], pred.iloc[a_position])
        print("coef is",coef)
        print('coef for |alpha(t)|>0.1 is',coef_a)
    else:
        print("coef is",coef)
        print("no result for |alpha(t)|>0.1.")

In [153]:
theta_list = np.linspace(0.2, 0.8, num=100)

H = 10
for i in range(len(pair)):
    print(pair[i])
    result_dict[i] = result_dict[i].dropna()
    s_1, s_2 = signal(result_dict[i], 0.114, train_beg, train_end, cv_beg, cv_end)
    y = result_dict[i].iloc[cv_beg: cv_end].iloc[H:]
    z_t = result_dict[i].iloc[cv_beg: cv_end].shift(10).iloc[H:]
    
    # optimize theta by maximizing coefficient
    coef_3_list = []
    for theta in theta_list:
        s_3 = signal3(theta, s_1, s_2)
        x_3 = sm.add_constant(s_3).shift(H)[H:]
        AR3 = sm.OLS(y, x_3)
        res3 = AR3.fit()
        pred3 = res3.predict(x_3)
        coef_3, p =spearmanr(y, pred3) 
        coef_3_list.append(coef_3)
    best_theta = theta_list[np.argmax(coef_3_list)]
    print("Optimal theta that maximize the coef is ", (best_theta))
    s_3 = signal3(best_theta, s_1, s_2)
    
    predict(s_1,y,H)
    predict(s_2,y,H)
    predict(s_3,y,H)
    
    print()

[3, 4]
Optimal theta that maximize the coef is  0.8
coef is 0.9472445628223136
no result for |alpha(t)|>0.1.
coef is 0.249363614525926
coef for |alpha(t)|>0.1 is 0.04245623953349738
coef is 0.9471804846725367
no result for |alpha(t)|>0.1.

[4, 5]
Optimal theta that maximize the coef is  0.8
coef is 0.9260771708412977
no result for |alpha(t)|>0.1.
coef is 0.044112795155415295
coef for |alpha(t)|>0.1 is -0.6
coef is 0.9209929736345951
no result for |alpha(t)|>0.1.

[2, 4]
Optimal theta that maximize the coef is  0.8
coef is 0.9497835315989768
no result for |alpha(t)|>0.1.
coef is 0.2587390114096382
coef for |alpha(t)|>0.1 is 0.22221855172839833
coef is 0.9498905147490468
no result for |alpha(t)|>0.1.

[3, 5]
Optimal theta that maximize the coef is  0.8
coef is 0.942352500208912
no result for |alpha(t)|>0.1.
coef is 0.19244375354062226
coef for |alpha(t)|>0.1 is 0.18370261616356873
coef is 0.9419798172408402
no result for |alpha(t)|>0.1.



# 5. Run your signal quality analysis using a testing sample C. Break the test sample into 4 quarters, and see how your results evolve from quarter to quarter. Analyze all results

In [154]:
H = 10
best_theta = 0.8
for i in range(len(pair)):
    print(pair[i])
    for j in range(4):
        print(f"Quarter {j+1}: ")
        interval = (test_end - test_beg) / 4
        quarter_beg = int(test_beg + j * interval)
        quarter_end = int(quarter_beg + (j + 1) * interval)

        s_1, s_2 = signal(result_dict[i], 0.114, train_beg, train_end, cv_beg=quarter_beg, cv_end=quarter_end)
        y = result_dict[i].iloc[quarter_beg: quarter_end].iloc[H:]
        z_t = result_dict[i].iloc[quarter_beg: quarter_end].shift(10).iloc[H:]
        
        s_3 = signal3(best_theta, s_1, s_2)

        predict(s_1,y,H)
        predict(s_2,y,H)
        predict(s_3,y,H)
        
    print()

[3, 4]
Quarter 1: 
coef is 0.7038531328319474
no result for |alpha(t)|>0.1.
coef is 0.6743510953542432
no result for |alpha(t)|>0.1.
coef is 0.7116632539601946
no result for |alpha(t)|>0.1.
Quarter 2: 
coef is 0.865547213136745
no result for |alpha(t)|>0.1.
coef is -0.0740278980595584
coef for |alpha(t)|>0.1 is 0.28253285897945135
coef is 0.8468131863944537
no result for |alpha(t)|>0.1.
Quarter 3: 
coef is 0.8398438164950207
no result for |alpha(t)|>0.1.
coef is 0.05525231015958749
coef for |alpha(t)|>0.1 is 0.360187200717894
coef is 0.8314508239852845
no result for |alpha(t)|>0.1.
Quarter 4: 
coef is 0.6825056518559607
no result for |alpha(t)|>0.1.
coef is 0.40043705803147794
coef for |alpha(t)|>0.1 is 0.5072268907563025
coef is 0.6830154775004095
no result for |alpha(t)|>0.1.

[4, 5]
Quarter 1: 
coef is 0.2542322225885119
no result for |alpha(t)|>0.1.
coef is 0.10263197274926641
no result for |alpha(t)|>0.1.
coef is 0.2003116539682022
no result for |alpha(t)|>0.1.
Quarter 2: 
coef is

For each quarter, when there is result for  |$\alpha(t)$|>0.1, the coefficient is larger
